version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: university_db
    environment:
      MYSQL_ROOT_PASSWORD: sasa
      MYSQL_DATABASE: db_universidad
      #MYSQL_USER: root
      #MYSQL_PASSWORD: sasa
      # In case that I want to use environmental variables
      # This is the command: MYSQL_DATABASE=mydatabase MYSQL_PASSWORD=rootpassword docker-compose up
      # MYSQL_DATABASE=${MYSQL_DATABASE}
      # MYSQL_ROOT_PASSWORD=${MYSQL_PASSWORD}
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - springboot-mysql-network

  springboot_app:
    build: .
    container_name: springboot_app
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/db_universidad?serverTimezone=Europe/Paris
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: sasa
      SPRING_JPA_HIBERNATE_DDL_AUTO: create-drop
      # SPRING_DATASOURCE_PASSWORD=${MYSQL_PASSWORD}
    depends_on:
      - mysql
    networks:
      - springboot-mysql-network

volumes:
  db_data:

networks:
  springboot-mysql-network:
    driver: bridge